name: Republish

on:
  schedule:
    - cron: '0 0 * * *'  # midnight daily
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --fail --request POST \
            --url  https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer ${{ secrets.PAGES_PAT }}"
